# Generated by Django 3.1.7 on 2021-04-26 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 22, 13, 56, 839115)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 22, 13, 56, 840112)),
        ),
    ]
