# Generated by Django 3.1.7 on 2021-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0002_auto_20210412_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='Matricula',
            new_name='Cedula',
        ),
        migrations.RenameField(
            model_name='personaladministrativo',
            old_name='Matricula',
            new_name='Cedula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='DiaDeIngreso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Riesgo',
            field=models.CharField(choices=[('R', 'Rojo'), ('M', 'Naranja'), ('A', 'Amarillo'), ('V', 'Verde')], default='V', max_length=1),
        ),
    ]
