# Generated by Django 3.1.7 on 2021-04-26 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0002_auto_20210425_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='nombre_reportado',
            new_name='nombre_encuestado',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 23, 19, 31, 829509)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 23, 19, 31, 830506)),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(default='xxxxxxxx', max_length=50, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='riesgo',
            field=models.CharField(choices=[('R', 'Rojo'), ('N', 'Naranja'), ('A', 'Amarillo'), ('V', 'Verde')], default='V', max_length=1, verbose_name='Riesgo'),
        ),
    ]
