# Generated by Django 3.1.7 on 2021-04-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0003_auto_20210412_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Matricula',
            field=models.CharField(max_length=9),
        ),
    ]
