# Generated by Django 3.1.7 on 2021-04-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ApellidoMaterno',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ApellidoPaterno',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
