# Generated by Django 3.1.7 on 2021-05-02 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0006_auto_20210425_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='Correo',
            field=models.EmailField(default='xxxxxx@xxxxxx.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profesores',
            name='Docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SRRC19.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 18, 3, 32, 905190)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 18, 3, 32, 906157)),
        ),
    ]
