# Generated by Django 3.2 on 2021-05-01 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0006_auto_20210425_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='Correo',
            field=models.EmailField(default='xxxxxx@xxxxxx.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='alumnobuscado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 16, 59, 0, 292631)),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 16, 59, 0, 293131)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
