# Generated by Django 3.1.7 on 2021-04-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0007_auto_20210414_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='PersonalAdministrativo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='ApellidoMaterno',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ApellidoPaterno',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
