# Generated by Django 3.1.7 on 2021-04-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0008_auto_20210414_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Matricula',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
