# Generated by Django 3.2 on 2021-05-10 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0009_merge_0007_auto_20210501_1659_0008_auto_20210501_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['ocupacion']},
        ),
        migrations.RemoveField(
            model_name='alumnobuscado',
            name='AsistirDiasSeguidos',
        ),
        migrations.RemoveField(
            model_name='alumnobuscado',
            name='GelSanitizante',
        ),
        migrations.RemoveField(
            model_name='alumnobuscado',
            name='NoTapeteSanitizante',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='CedulaProfesional',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='NombreCompleto',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='AsistirDiasSeguidos',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='GelSanitizante',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='NoTapeteSanitizante',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 20, 54, 112981)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 20, 54, 114013)),
        ),
    ]
