# Generated by Django 3.2 on 2021-05-10 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0010_auto_20210509_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 29, 34, 245769)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 29, 34, 246768)),
        ),
    ]
