# Generated by Django 3.1.7 on 2021-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0010_auto_20210414_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
