# Generated by Django 3.1.7 on 2021-04-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0011_auto_20210414_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
