# Generated by Django 3.2 on 2021-05-10 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0011_auto_20210509_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 32, 17, 969245)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 32, 17, 970238)),
        ),
    ]
