# Generated by Django 3.1.7 on 2021-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0015_auto_20210414_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='ocupacion',
            field=models.CharField(choices=[('A', 'Alumno'), ('D', 'Docente'), ('P', 'Personal Administrativo')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
