# Generated by Django 3.1.7 on 2021-04-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0016_auto_20210414_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='riesgo',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1),
        ),
    ]
