# Generated by Django 3.1.7 on 2021-04-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0020_reportes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reportes',
            new_name='Reporte',
        ),
    ]
