# Generated by Django 3.1.7 on 2021-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0021_auto_20210416_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='matricula',
            field=models.CharField(default='xxxxxxxx', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Comentarios',
            field=models.CharField(default='', max_length=255),
        ),
    ]
