# Generated by Django 3.1.7 on 2021-04-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0023_auto_20210416_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='matricula',
            new_name='matricula_reportado',
        ),
    ]
