# Generated by Django 3.1.7 on 2021-04-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0024_auto_20210416_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
