# Generated by Django 3.1.7 on 2021-04-17 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRC19', '0029_auto_20210417_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='hora',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 16, 22, 48, 101377)),
        ),
    ]
